[package]
name = "nps"
version = "1.0.0"
edition = "2021"
authors = ["Osef0760 <osefcode@gmail.com"]

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }
reqwest = { version = "0.12.12", features = ["blocking"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
